import sqlite3
db = sqlite3.connect(':memory:')
db.enable_load_extension(True)
db.load_extension('./build/libgraph')
db.execute("CREATE VIRTUAL TABLE graph USING graph()")
print("Test: CREATE (:Person)")
r = db.execute("SELECT cypher_execute('CREATE (:Person)')").fetchone()
print(r[0])
print("Test: CREATE (:A)-[:KNOWS]->(:B)")
r = db.execute("SELECT cypher_execute('CREATE (:A)-[:KNOWS]->(:B)')").fetchone()
print(r[0])
print("Nodes:", db.execute('SELECT COUNT(*) FROM graph_nodes').fetchone()[0])
print("Edges:", db.execute('SELECT COUNT(*) FROM graph_edges').fetchone()[0])
print("Test: MATCH (:A)-[r:KNOWS]->(:B) RETURN r")
r = db.execute("SELECT cypher_execute('MATCH (:A)-[r:KNOWS]->(:B) RETURN r')").fetchone()
print(r[0])
