blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/agentflare-ai/sqlite-graph/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/agentflare-ai/sqlite-graph/wiki
    about: Read the documentation and guides
  - name: 🔒 Security Vulnerability
    url: https://github.com/agentflare-ai/sqlite-graph/security/advisories/new
    about: Report a security vulnerability privately (do not use public issues)
